import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("theme")?.value ?? "light";
  console.log("theme", theme);

  return (
    <html lang="en">
      <body className={`${inter.className} ${theme === "dark" ? "dark" : ""}`}>
        {children}
      </body>
    </html>
  );
}
