import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { getCookies } from "./actions";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // This is in server
  const theme = await getCookies("theme", "light");

  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} dark:bg-black dark:text-white ${theme === "dark" ? "dark" : ""}`}
      >
        {children}
      </body>
    </html>
  );
}
